-- ============================================
-- Travel Oceans CMS - Database Schema
-- ============================================

CREATE DATABASE IF NOT EXISTS `traveloceans` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `traveloceans`;

-- --------------------------------------------------------
-- Admin users
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `admins` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `email` VARCHAR(120) DEFAULT NULL,
  `full_name` VARCHAR(120) DEFAULT NULL,
  `role` ENUM('superadmin','editor') NOT NULL DEFAULT 'editor',
  `last_login` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Default admin (username: admin | password: admin123)
-- Password hash will be regenerated by install.php on first run

-- --------------------------------------------------------
-- Site settings
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `settings` (
  `setting_key` VARCHAR(80) NOT NULL,
  `setting_value` TEXT,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `settings` (`setting_key`,`setting_value`) VALUES
('site_name','Travel Oceans'),
('site_tagline','Travel Across the Oceans'),
('site_email','info@traveloceans.eu'),
('site_phone_1','+351 969 756 675'),
('site_phone_2','+351 963 728 746'),
('site_phone_3','+351 966 396 601'),
('site_address','Lisbon, Portugal'),
('site_url','www.traveloceans.eu'),
('whatsapp','+351969756675'),
('facebook','https://facebook.com/traveloceans'),
('instagram','https://instagram.com/traveloceans'),
('linkedin','https://linkedin.com/company/traveloceans'),
('youtube','https://youtube.com/@traveloceans'),
('important_notice','Travel Oceans provides support, guidance, information, coordination, and assistance services only. We do not provide legal advice, immigration legal services, legal representation, tax advice, or regulated professional services. Where professional legal, immigration, tax, or financial expertise is required, we can refer clients to qualified and licensed professionals.'),
('about_short','Travel Oceans is a Portugal-based consultancy helping travellers, expats, entrepreneurs, and students with relocation, business, study and concierge services. We simplify complex processes so you can focus on your journey.'),
('footer_about','Travel Oceans — your trusted partner for relocation, travel, business, and study services in Portugal, Spain, and Germany. Practical guidance. Personalized support. Local expertise.'),
('meta_description','Travel Oceans offers relocation, visa, business formation, study abroad and concierge services in Portugal, Spain and Germany. Your trusted partner for travel, work and study.'),
('meta_keywords','travel oceans, portugal relocation, portugal visa, business formation portugal, study in spain, study in germany, berlin courses, concierge portugal');

-- --------------------------------------------------------
-- Homepage slider / hero slides
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `slides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `subtitle` TEXT,
  `description` TEXT,
  `button_text` VARCHAR(80) DEFAULT 'Learn More',
  `button_link` VARCHAR(255) DEFAULT '#',
  `image` VARCHAR(255) DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `slides` (`title`,`subtitle`,`description`,`button_text`,`button_link`,`sort_order`) VALUES
('Moving to Portugal?','Relocation, Travel & Business Services','Travel Oceans is here to guide and support you every step of the way. From your first idea to settling in, we are with you.','Our Services','services.php',1),
('Immigration Process Starts Here','Visa & Travel Planning Made Simple','We simplify visa processing and travel planning so you can focus on your journey. From tourist and business visas to complete travel assistance, our expert consultants ensure a smooth, stress-free experience from start to finish.','Get Started','contact.php',2),
('Portugal Relocation, Business & Concierge','One Partner. Endless Support.','We help individuals, families, entrepreneurs, freelancers, remote workers, and investors navigate their move to Portugal with practical guidance, personalized support, and local expertise.','Contact Us','contact.php',3),
('Study Abroad in Spain & Germany','Bachelor & Master Programs','Top universities, affordable tuition, post-study work opportunities and full visa assistance for Spain and Germany.','Explore Programs','study-spain.php',4);

-- --------------------------------------------------------
-- Services (Relocation, Visa, Business, Tourism etc.)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(120) NOT NULL UNIQUE,
  `title` VARCHAR(160) NOT NULL,
  `short_description` TEXT,
  `full_description` LONGTEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-briefcase',
  `image` VARCHAR(255) DEFAULT NULL,
  `color` VARCHAR(20) DEFAULT '#0d6efd',
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `show_on_home` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `button_text` VARCHAR(255) NOT NULL DEFAULT 'Enquire About This Service',
  `button_link` VARCHAR(255) NOT NULL DEFAULT 'contact.php',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `services` (`slug`,`title`,`short_description`,`icon`,`color`,`sort_order`,`button_text`,`button_link`) VALUES
('relocation','Relocation Assistance','Pre-arrival planning, housing, settling-in help & family relocation support.','bi-airplane','#1d6cb5',1,'Enquire About This Service','contact.php'),
('visa','Visa & Application Support','Pathway guidance, document assistance, appointment booking & application support.','bi-file-earmark-text','#0dcaf0',2,'Enquire About This Service','contact.php'),
('business-entrepreneur','Business & Entrepreneur Support','Setup guidance, self-employment, market entry, networking.','bi-handshake','#198754',3,'Enquire About This Service','contact.php'),
('consulting','Business Consulting','Strategy, planning, operations advice, business growth & project support.','bi-graph-up-arrow','#6610f2',4,'Enquire About This Service','contact.php'),
('tours-concierge','Tours & Concierge Services','City & cultural tours, travel planning, reservations & local experiences.','bi-palm-tree','#fd7e14',5,'Enquire About This Service','contact.php'),
('referrals','Referrals & Local Connections','Accountants, lawyers, real estate & insurance introductions.','bi-people','#d63384',6,'Enquire About This Service','contact.php'),
('airport-arrival','Airport & Arrival Support','Airport pickup, orientation, practical assistance & local guidance.','bi-car-front','#20c997',7,'Enquire About This Service','contact.php'),
('travel-planning','Travel Planning','Flights & hotels, itinerary planning, activities & custom trips.','bi-globe','#0d6efd',8,'Enquire About This Service','contact.php'),
('property','Property Assistance','Property search, viewings, rental guidance & area information.','bi-house','#6c757d',9,'Enquire About This Service','contact.php'),
('ongoing-support','Ongoing Support','24/7 guidance, long-term support & peace of mind.','bi-chat-square-text','#ffc107',10,'Enquire About This Service','contact.php');

-- Service feature bullets
CREATE TABLE IF NOT EXISTS `service_features` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` INT UNSIGNED NOT NULL,
  `feature_text` VARCHAR(255) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `service_id` (`service_id`),
  CONSTRAINT `fk_sf_service` FOREIGN KEY (`service_id`) REFERENCES `services`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `service_features` (`service_id`,`feature_text`,`sort_order`) VALUES
(1,'Pre-arrival planning',1),(1,'Housing search support',2),(1,'Settling-in help',3),(1,'Family relocation',4),(1,'Cost of living guidance',5),(1,'Area and city recommendations',6),(1,'Utility setup guidance',7),(1,'School and family relocation assistance',8),
(2,'Visa pathway guidance',1),(2,'Document assistance',2),(2,'Appointment booking',3),(2,'Application support',4),(2,'Relocation planning for visa applicants',5),(2,'Ongoing support throughout the relocation process',6),
(3,'Business startup guidance',1),(3,'Self-employment activity registration',2),(3,'Business planning consultations',3),(3,'Market entry guidance',4),(3,'Freelance and remote worker support',5),(3,'Business networking opportunities',6),(3,'Supplier and service provider introductions',7),
(4,'Strategic business consulting',1),(4,'Operations and management advice',2),(4,'Business development planning',3),(4,'Market research support',4),(4,'Project management assistance',5),(4,'Growth strategy consultations',6),
(5,'Personalized Portugal orientation tours',1),(5,'Local area familiarization',2),(5,'Tourist information services',3),(5,'Reservation assistance',4),(5,'Travel planning support',5),(5,'Restaurant and activity recommendations',6),(5,'Lifestyle and integration support',7),
(6,'Introductions to accountants',1),(6,'Introductions to real estate professionals',2),(6,'Introductions to mortgage specialists',3),(6,'Introductions to insurance providers',4),(6,'Introductions to business service providers',5),(6,'Supplier sourcing and business matchmaking',6),
(7,'Airport meet-and-greet coordination',1),(7,'Local orientation assistance',2),(7,'Banking appointment support',3),(7,'Administrative guidance',4),(7,'Everyday practical support for newcomers',5),
(8,'Flights & hotels',1),(8,'Itinerary planning',2),(8,'Activities & tickets',3),(8,'Custom trips',4),
(9,'Property search',1),(9,'Viewings support',2),(9,'Rental guidance',3),(9,'Area information',4),
(10,'24/7 guidance',1),(10,'Long-term support',2),(10,'Any time help',3),(10,'Peace of mind',4);

-- --------------------------------------------------------
-- Business formation services (Start Business in Portugal)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `business_services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-briefcase',
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `business_services` (`title`,`description`,`icon`,`sort_order`) VALUES
('Company Registration','Fast and hassle-free company setup with the right structure for your business.','bi-file-earmark-text',1),
('Business Structure Guidance','Choose the right legal structure (LDA, SA, sole proprietorship) for your goals.','bi-diagram-3',2),
('Tax & Compliance Assistance','Stay compliant with Portuguese regulations, NIF, VAT and accounting.','bi-cash-stack',3),
('Support for Foreign Entrepreneurs','Dedicated support for non-residents and international founders.','bi-globe2',4),
('End-to-End Business Setup Solutions','We handle it all so you can focus on growing your business.','bi-handshake',5);

-- --------------------------------------------------------
-- Why Choose Portugal (country highlight reasons)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `portugal_reasons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-geo-alt',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `portugal_reasons` (`title`,`description`,`icon`,`sort_order`) VALUES
('Strategic European Location','Gateway between Europe, Africa and the Americas — perfect for global business.','bi-geo-alt',1),
('Business-Friendly Environment','Low corporate tax, incentives for startups, and welcoming authorities.','bi-briefcase',2),
('Access to EU Markets','Trade freely within the European Union with a Portuguese entity.','bi-globe-europe-africa',3),
('Attractive Opportunities for Growth','Thriving tech, tourism and real estate sectors — a hub for entrepreneurs and investors.','bi-graph-up',4);

-- --------------------------------------------------------
-- Study Abroad Programs (Spain & Germany)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `programs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(120) NOT NULL UNIQUE,
  `country` VARCHAR(60) NOT NULL,
  `city` VARCHAR(60) DEFAULT NULL,
  `title` VARCHAR(200) NOT NULL,
  `tagline` VARCHAR(255) DEFAULT NULL,
  `description` LONGTEXT,
  `hero_image` VARCHAR(255) DEFAULT NULL,
  `flag_emoji` VARCHAR(20) DEFAULT '',
  `accent_color` VARCHAR(20) DEFAULT '#0d6efd',
  `meta_title` VARCHAR(200) DEFAULT NULL,
  `meta_description` TEXT,
  `sort_order` INT NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `programs` (`slug`,`country`,`city`,`title`,`tagline`,`description`,`flag_emoji`,`accent_color`,`sort_order`) VALUES
('study-spain','Spain',NULL,'Study in Spain','Your Future. Our Purpose.','Top Spanish universities offering Bachelor and Master programs. Affordable tuition, post-study work opportunities and a vibrant Mediterranean lifestyle — with no IELTS required and full visa assistance.','🇪🇸','#aa1518',1),
('study-germany','Germany',NULL,'Study in Germany','World-Class Education. Global Career.','Low tuition, world-renowned universities, post-study work visa up to 18 months, and PR pathway opportunities. Safe, vibrant and internationally diverse.','🇩🇪','#000000',2),
('study-berlin','Germany','Berlin','Learn German in Berlin','Live • Learn • Connect','German courses A1–C2, flexible accommodation options (homestay, residence, private apartment, hotel) and an international student community in one of Europe''s most exciting cities.','🇩🇪','#ffce00',3);

-- Program highlights / features
CREATE TABLE IF NOT EXISTS `program_highlights` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `program_id` INT UNSIGNED NOT NULL,
  `feature_text` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(80) DEFAULT 'bi-check2',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `program_id` (`program_id`),
  CONSTRAINT `fk_ph_program` FOREIGN KEY (`program_id`) REFERENCES `programs`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `program_highlights` (`program_id`,`feature_text`,`icon`,`sort_order`) VALUES
(1,'Top Universities','bi-mortarboard',1),
(1,'Affordable Tuition Fees','bi-cash',2),
(1,'Post-Study Work Opportunities','bi-briefcase',3),
(1,'Vibrant Lifestyle','bi-sun',4),
(1,'Learn Spanish','bi-translate',5),
(1,'Bachelor''s & Master''s Programs','bi-book',6),
(1,'No IELTS Required','bi-check2-circle',7),
(1,'Visa Assistance Provided','bi-passport',8),
(2,'Low Tuition Fees','bi-cash',1),
(2,'Bachelor''s: 3 Years | Master''s: 1.5–2 Years','bi-calendar3',2),
(2,'Post-Study Work Visa up to 18 Months','bi-passport',3),
(2,'World-Class Education','bi-mortarboard',4),
(2,'Work Opportunities During Studies','bi-briefcase',5),
(2,'Safe & Vibrant Lifestyle','bi-shield-check',6),
(2,'PR Pathway Opportunities','bi-globe-europe-africa',7),
(3,'German Courses A1–C2','bi-translate',1),
(3,'Flexible Accommodation Options','bi-house',2),
(3,'International Student Community','bi-people',3),
(3,'Central European Hub','bi-geo-alt',4),
(3,'Excellent Education Opportunities','bi-mortarboard',5),
(3,'Career & Networking Prospects','bi-briefcase',6),
(3,'Modern Public Transport','bi-bus-front',7),
(3,'Rich Culture & History','bi-bank',8),
(3,'Globally Recognized Language Skills','bi-globe',9),
(3,'Affordable Student Lifestyle','bi-cash-coin',10);

-- Program details (extra info like duration, fees, eligibility)
CREATE TABLE IF NOT EXISTS `program_details` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `program_id` INT UNSIGNED NOT NULL,
  `detail_key` VARCHAR(80) NOT NULL,
  `detail_value` VARCHAR(255) NOT NULL,
  `icon` VARCHAR(80) DEFAULT 'bi-info-circle',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `program_id` (`program_id`),
  CONSTRAINT `fk_pd_program` FOREIGN KEY (`program_id`) REFERENCES `programs`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `program_details` (`program_id`,`detail_key`,`detail_value`,`icon`,`sort_order`) VALUES
(1,'Tuition','Affordable','bi-cash',1),
(1,'Duration','Bachelor: 3–4 Years · Master: 1–2 Years','bi-calendar3',2),
(1,'Language','English / Spanish','bi-translate',3),
(1,'Intakes','September / January','bi-calendar-event',4),
(1,'IELTS','Not Required','bi-check2-circle',5),
(2,'Tuition','Low / Free at Public Universities','bi-cash',1),
(2,'Duration','Bachelor: 3 Years · Master: 1.5–2 Years','bi-calendar3',2),
(2,'PSW Visa','Up to 18 Months','bi-passport',3),
(2,'Language','English / German','bi-translate',4),
(2,'Intakes','October / April','bi-calendar-event',5),
(3,'Levels','A1 – C2','bi-translate',1),
(3,'Start','Every Monday','bi-calendar3',2),
(3,'Class Size','Small Interactive','bi-people',3),
(3,'Certificate','Recognized','bi-award',4);

-- --------------------------------------------------------
-- Why choose us (reasons)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `why_choose` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-check-circle',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `why_choose` (`title`,`description`,`icon`,`sort_order`) VALUES
('Personalized Support','Tailored support based on your individual travel, relocation, business, and lifestyle needs.','bi-person-heart',1),
('Practical Guidance','Clear and practical guidance to help you understand processes, prepare documentation and plan your move.','bi-compass',2),
('Local Knowledge','Deep understanding of Portugal''s culture, lifestyle, business environment, and day-to-day living.','bi-globe-europe-africa',3),
('Reliable Assistance','From initial planning to settling in — ongoing assistance throughout your journey.','bi-shield-check',4),
('Trusted Professional Network','Connections to qualified accountants, lawyers, real estate specialists and service providers.','bi-people-fill',5),
('One Point of Contact','We simplify the process by coordinating multiple services, saving you time and stress.','bi-telephone',6),
('Honest & Transparent Approach','Clear communication, realistic expectations, and your interests first.','bi-hand-thumbs-up',7);

-- --------------------------------------------------------
-- Documentation services
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `documentation_categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-file-earmark-text',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `documentation_categories` (`title`,`description`,`icon`,`sort_order`) VALUES
('International Documentation','End-to-end documentation services with accurate, compliant and well-structured paperwork for India and abroad.','bi-globe',1),
('Within Portugal Services','NIF, NISS, AIMA, residence renewal, translations and more — we coordinate everything.','bi-geo-alt',2);

CREATE TABLE IF NOT EXISTS `documentation_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `description` TEXT,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `category_id` (`category_id`),
  CONSTRAINT `fk_di_cat` FOREIGN KEY (`category_id`) REFERENCES `documentation_categories`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `documentation_items` (`category_id`,`title`,`description`,`sort_order`) VALUES
(1,'Apostille services in New Delhi',NULL,1),
(1,'Translation and Notary of documents',NULL,2),
(1,'Police Clearance Certificate in India (PCC)',NULL,3),
(1,'Police Clearance Certificate in overseas posts / mission',NULL,4),
(1,'Attestation and Notarization of Documents',NULL,5),
(1,'Assistance in OCI Card (Overseas Citizens of India)',NULL,6),
(1,'Portuguese Criminal Record',NULL,7),
(1,'Removal of SIS – Schengen Information System',NULL,8),
(1,'Embassy appointments',NULL,9),
(2,'NIF / NISS / SNS Support and Guidance',NULL,1),
(2,'AIMA Services Support including Appointment assistance',NULL,2),
(2,'Residence Renewal Support and Guidance',NULL,3),
(2,'PR Appointment Support and Guidance',NULL,4),
(2,'Finance Address change or address Removal Support',NULL,5),
(2,'Translation and Notary Services (Standard or same day)',NULL,6),
(2,'Driving Licence Assistance and Support',NULL,7),
(2,'Documentation collection and support',NULL,8),
(2,'Immigration Guidance and Support',NULL,9),
(2,'Student admission and administrative Support',NULL,10),
(2,'Legal assistance arrangements',NULL,11),
(2,'Housing Support and Guidance',NULL,12);

-- --------------------------------------------------------
-- Portugal destination (Things to do)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `portugal_things` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT,
  `icon` VARCHAR(80) DEFAULT 'bi-camera',
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `portugal_things` (`title`,`description`,`icon`,`sort_order`) VALUES
('Explore historic castles, palaces and charming old towns','Walk through centuries of history from Moorish castles to Baroque palaces.','bi-bank',1),
('Walk through colorful streets and scenic landscapes','From pastel-painted Lisbon to the vineyards of the Douro Valley.','bi-camera',2),
('Relax on beautiful beaches and coastal towns','Over 800 km of Atlantic coastline — Algarve, Cascais, Comporta.','bi-water',3),
('Take a boat trip along the Douro River or around the coast','Cruise through the wine valley or sail to the Berlengas archipelago.','bi-tsunami',4),
('Discover nature trails, stunning views and outdoor activities','Hike Madeira, Azores or the Sintra mountains.','bi-tree',5),
('Enjoy local markets, shopping and traditional handmade items','From Lisbon''s Feira da Ladra to Porto''s Bolhão market.','bi-bag',6),
('Experience local festivals, fado music and vibrant culture','Year-round festivities, traditional Fado and street celebrations.','bi-music-note',7);

-- --------------------------------------------------------
-- Testimonials
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `testimonials` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(120) NOT NULL,
  `client_role` VARCHAR(160) DEFAULT NULL,
  `client_country` VARCHAR(80) DEFAULT NULL,
  `client_photo` VARCHAR(255) DEFAULT NULL,
  `rating` TINYINT NOT NULL DEFAULT 5,
  `message` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `testimonials` (`client_name`,`client_role`,`client_country`,`rating`,`message`,`sort_order`) VALUES
('Rahul S.','Software Engineer','India',5,'Travel Oceans made my Portugal relocation smooth and stress-free. From visa to housing, everything was perfectly coordinated.',1),
('Maria L.','Entrepreneur','Brazil',5,'I started my company in Lisbon with their help. The team guided me through every step — registration, tax, banking. Highly recommended.',2),
('James K.','Master''s Student','Nigeria',5,'Got into a top university in Spain with full scholarship guidance and visa support. They really care about your future.',3),
('Anika P.','Freelancer','Germany',5,'The Berlin German course was perfect — small classes, great accommodation, and an amazing international community. Thank you!',4);

-- --------------------------------------------------------
-- Contact messages
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `contact_messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(160) NOT NULL,
  `phone` VARCHAR(60) DEFAULT NULL,
  `subject` VARCHAR(200) DEFAULT NULL,
  `service_interest` VARCHAR(120) DEFAULT NULL,
  `message` TEXT NOT NULL,
  `ip_address` VARCHAR(60) DEFAULT NULL,
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Newsletter subscriptions
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `subscribers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(160) NOT NULL UNIQUE,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Generic CMS Pages
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(160) NOT NULL UNIQUE,
  `title` VARCHAR(200) NOT NULL,
  `content` LONGTEXT,
  `meta_description` TEXT,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `pages` (`slug`,`title`,`content`) VALUES
('about','About Travel Oceans','<p>Travel Oceans is a Portugal-based consultancy dedicated to helping travellers, expats, entrepreneurs, students and families navigate their journey with practical guidance, personalized support and trusted local connections.</p><p>Whether you are moving to Portugal, starting a business, studying in Spain or Germany, or simply planning a trip, our mission is to make the process smooth, transparent and stress-free.</p><p>Our team combines international experience with deep local knowledge of Portuguese, Spanish and German processes — providing a single point of contact for everything you need.</p>'),
('privacy','Privacy Policy','<p>This page describes how Travel Oceans collects, uses and protects your personal information.</p><p>We only collect information you voluntarily provide through our contact forms and email communications. We never sell your data and we use it solely to respond to your enquiries and provide requested services.</p>'),
('terms','Terms of Service','<p>By using traveloceans.eu you agree to the following terms. Travel Oceans provides consulting, coordination and referral services only. We do not provide legal, tax or regulated professional advice.</p>');

-- --------------------------------------------------------
-- Free visa assessment submissions
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `visa_assessments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_legal_name` VARCHAR(200) NOT NULL,
  `dob` DATE DEFAULT NULL,
  `gender` VARCHAR(20) DEFAULT NULL,
  `birthplace_country` VARCHAR(100) DEFAULT NULL,
  `birthplace_state` VARCHAR(100) DEFAULT NULL,
  `birthplace_city` VARCHAR(100) DEFAULT NULL,
  `nationality` VARCHAR(200) DEFAULT NULL,
  `passport_number` VARCHAR(50) DEFAULT NULL,
  `passport_issue` DATE DEFAULT NULL,
  `passport_expiry` DATE DEFAULT NULL,
  `current_residency` VARCHAR(200) DEFAULT NULL,
  `address_country` VARCHAR(100) DEFAULT NULL,
  `address_state` VARCHAR(100) DEFAULT NULL,
  `address_city` VARCHAR(100) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `phone` VARCHAR(60) DEFAULT NULL,
  `email` VARCHAR(160) NOT NULL,
  `marital_status` VARCHAR(50) DEFAULT NULL,
  `spouse_partner_details` TEXT DEFAULT NULL,
  `dependent_children` INT UNSIGNED DEFAULT 0,
  `children_json` JSON DEFAULT NULL,
  `family_target_country` VARCHAR(10) DEFAULT NULL,
  `family_target_details` TEXT DEFAULT NULL,
  `target_countries` VARCHAR(200) DEFAULT NULL,
  `visa_category` VARCHAR(100) DEFAULT NULL,
  `intended_travel_date` DATE DEFAULT NULL,
  `expected_duration` VARCHAR(50) DEFAULT NULL,
  `previous_visa_yesno` VARCHAR(10) DEFAULT NULL,
  `previous_visa_details` TEXT DEFAULT NULL,
  `refusal_yesno` VARCHAR(10) DEFAULT NULL,
  `refusal_details` TEXT DEFAULT NULL,
  `education_level` VARCHAR(100) DEFAULT NULL,
  `institution_country` VARCHAR(200) DEFAULT NULL,
  `field_of_study` VARCHAR(200) DEFAULT NULL,
  `graduation_year` VARCHAR(10) DEFAULT NULL,
  `native_language` VARCHAR(100) DEFAULT NULL,
  `english_proficiency` VARCHAR(50) DEFAULT NULL,
  `english_test_score` VARCHAR(100) DEFAULT NULL,
  `other_languages` TEXT DEFAULT NULL,
  `french_spanish_test_score` VARCHAR(100) DEFAULT NULL,
  `employment_status` VARCHAR(50) DEFAULT NULL,
  `job_title` VARCHAR(200) DEFAULT NULL,
  `employer_industry` VARCHAR(200) DEFAULT NULL,
  `years_experience` VARCHAR(50) DEFAULT NULL,
  `employment_summary` TEXT DEFAULT NULL,
  `employer1_details` TEXT DEFAULT NULL,
  `employer2_details` TEXT DEFAULT NULL,
  `source_of_funds` VARCHAR(100) DEFAULT NULL,
  `liquid_funds` VARCHAR(100) DEFAULT NULL,
  `monthly_income` VARCHAR(50) DEFAULT NULL,
  `assets_yesno` VARCHAR(10) DEFAULT NULL,
  `assets_summary` TEXT DEFAULT NULL,
  `travel_history_countries` TEXT DEFAULT NULL,
  `valid_visas_yesno` VARCHAR(10) DEFAULT NULL,
  `valid_visas_list` TEXT DEFAULT NULL,
  `criminal_record_yesno` VARCHAR(10) DEFAULT NULL,
  `criminal_details` TEXT DEFAULT NULL,
  `medical_conditions_yesno` VARCHAR(10) DEFAULT NULL,
  `medical_details` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(60) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `admin_notes` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `email` (`email`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
