-- ============================================
-- Visa Assessment — Updated Schema (calendar dates,
-- linked country/state/city, JSON children, separate table)
-- ============================================

CREATE TABLE IF NOT EXISTS `visa_assessments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_legal_name` VARCHAR(200) NOT NULL,
  `dob` DATE DEFAULT NULL,
  `gender` VARCHAR(20) DEFAULT NULL,
  `birthplace_country` VARCHAR(100) DEFAULT NULL,
  `birthplace_state` VARCHAR(100) DEFAULT NULL,
  `birthplace_city` VARCHAR(100) DEFAULT NULL,
  `nationality` VARCHAR(200) DEFAULT NULL,
  `passport_number` VARCHAR(50) DEFAULT NULL,
  `passport_issue` DATE DEFAULT NULL,
  `passport_expiry` DATE DEFAULT NULL,
  `current_residency` VARCHAR(200) DEFAULT NULL,
  `address_country` VARCHAR(100) DEFAULT NULL,
  `address_state` VARCHAR(100) DEFAULT NULL,
  `address_city` VARCHAR(100) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `phone` VARCHAR(60) DEFAULT NULL,
  `email` VARCHAR(160) NOT NULL,
  `marital_status` VARCHAR(50) DEFAULT NULL,
  `spouse_partner_details` TEXT DEFAULT NULL,
  `dependent_children` INT UNSIGNED DEFAULT 0,
  `children_json` JSON DEFAULT NULL,
  `family_target_country` VARCHAR(10) DEFAULT NULL,
  `family_target_details` TEXT DEFAULT NULL,
  `target_countries` VARCHAR(200) DEFAULT NULL,
  `visa_category` VARCHAR(100) DEFAULT NULL,
  `intended_travel_date` DATE DEFAULT NULL,
  `expected_duration` VARCHAR(50) DEFAULT NULL,
  `previous_visa_yesno` VARCHAR(10) DEFAULT NULL,
  `previous_visa_details` TEXT DEFAULT NULL,
  `refusal_yesno` VARCHAR(10) DEFAULT NULL,
  `refusal_details` TEXT DEFAULT NULL,
  `education_level` VARCHAR(100) DEFAULT NULL,
  `institution_country` VARCHAR(200) DEFAULT NULL,
  `field_of_study` VARCHAR(200) DEFAULT NULL,
  `graduation_year` VARCHAR(10) DEFAULT NULL,
  `native_language` VARCHAR(100) DEFAULT NULL,
  `english_proficiency` VARCHAR(50) DEFAULT NULL,
  `english_test_score` VARCHAR(100) DEFAULT NULL,
  `other_languages` TEXT DEFAULT NULL,
  `french_spanish_test_score` VARCHAR(100) DEFAULT NULL,
  `employment_status` VARCHAR(50) DEFAULT NULL,
  `job_title` VARCHAR(200) DEFAULT NULL,
  `employer_industry` VARCHAR(200) DEFAULT NULL,
  `years_experience` VARCHAR(50) DEFAULT NULL,
  `employment_summary` TEXT DEFAULT NULL,
  `employer1_details` TEXT DEFAULT NULL,
  `employer2_details` TEXT DEFAULT NULL,
  `source_of_funds` VARCHAR(100) DEFAULT NULL,
  `liquid_funds` VARCHAR(100) DEFAULT NULL,
  `monthly_income` VARCHAR(50) DEFAULT NULL,
  `assets_yesno` VARCHAR(10) DEFAULT NULL,
  `assets_summary` TEXT DEFAULT NULL,
  `travel_history_countries` TEXT DEFAULT NULL,
  `valid_visas_yesno` VARCHAR(10) DEFAULT NULL,
  `valid_visas_list` TEXT DEFAULT NULL,
  `criminal_record_yesno` VARCHAR(10) DEFAULT NULL,
  `criminal_details` TEXT DEFAULT NULL,
  `medical_conditions_yesno` VARCHAR(10) DEFAULT NULL,
  `medical_details` TEXT DEFAULT NULL,
  `ip_address` VARCHAR(60) DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
  `is_read` TINYINT(1) NOT NULL DEFAULT 0,
  `admin_notes` TEXT DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `email` (`email`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
